### ISSUE TITLE
TDI Strategy Compile error ?

### ISSUE THREAD

**Issue by mavidelisi** [EA31337/Strategy-TDI#3]
the source code gives compile error, I think there is a situation related to the framework version. i couldn't find the v3000.1 version.  can you add the v3.000.1 framework to github as well?
Thank you.
![Screenshot 2023-08-27 112238](https://github.com/EA31337/Strategy-TDI/assets/14947927/76377395-f588-441e-9dc3-5a128ded7770)

**Comment by kenorb** [comment]
You need to compile it with v3.000 or v3.000.1 version of classes/framework.

- https://github.com/EA31337/EA31337-classes/releases/tag/v3.000
- https://github.com/EA31337/EA31337-classes/releases/tag/v3.000.1

This version is split from v2.010 which should also work.

**Comment by mavidelisi** [comment]
he's still making mistakes. Is it possible to give it all ?
![Screenshot 2023-08-27 123240](https://github.com/EA31337/Strategy-TDI/assets/14947927/3c808640-88af-4871-9b31-4c8e42565b9b)

**Comment by mavidelisi** [comment]
I downloaded the latest EA31337 v3000.1 and it was deleted later. Could it be related to the master version?

**Comment by kenorb** [comment]
Could be related to different strategy versions. For `v3.000` you need `v2.000-dev` version of strategies (not `master`). Otherwise you can go back to `v2.013.1`, then strategies's `master` branch should work.
You can also switch `EA31337` repo to `dev` then reset all submodules to their corresponding HEADs, it should also work (e.g. `git submodule update --init`).
